package cordova.plugin.smartoneprinter;

import android.R.integer;
import android.app.PendingIntent.CanceledException;

public class Order {
	
	public static final String[][] OrderMessage= {{"",""},
												 {"HT 横向跳格","09"},
												 {"LF 打印并走纸一行","0A"},
												 {"FF 打印并走纸","0C"},
												 {"CR 打印并回车","0D"},
												 {"CAN 页模式下删除打印缓冲区内容","18"},
												 {"DLE EOT n实时状态传输 例n=1","100401"},
												 {"DLE ENQ n实时请求 例n=1","100501"},
												 {"ESC FF页模式下打印","1B0C"},
												 {"ESC SP n 设置字符右间距 例n=0","1B2000"},
												 {"ESC ! n 选择打印模式 例n=0","1B2100"},
												 {"ESC $ nL nH 设置横向绝对打印位置 例nL=48,nH=48","1B243030"},
												 {"ESC % n 选择/取消用户自定义字符 例n=0","1B2500"},
												 {"ESC & y c1 c2 [x1 d1...d(y * x1)]...[xk dk..d(y * xk)]定义用户自定义字符 例y=3,c1=48,c2=48,x=12, 48","1B260330300C30"},
												 {"ESC * m nL nH d1...dk 选择位图模式 例 m=0,nl=0,nh=48,d=1","1B2400003001"},
												 {"ESC -n 选择/取消下划线模式 例n=48","1B2D30"},
												 {"ESC 2 设置默认行高","1B32"},
												 {"ESC 3 n 设置行高 例n=48","1B3330"},
												 {"ESC ? n 取消用户自定义字符 例n=48","1B3F30"},
												 {"ESC @ 初始化打印机","1B40"},
												 {"ESC D n1...nk NUL 设置横向跳格位置 例n=255 k=0","1B44FF00"},
												 {"ESC E n 选择/取消加粗模式 例n=0","1B4500"},
												 {"ESC G n 选择/取消双重打印模式 例n=0","1B4700"},
												 {"ESC J n 打印并走纸 例n=1","1B4A01"},
												 {"ESC L n 选择页模式","1B4C"},
												 {"ESC M n 选择字体 例n=0","1B4D00"},
												 {"ESC R n 选择国际字符集 例n=0","1B5200"},
												 {"ESC S n 选择标准模式","1B53"},
												 {"ESC T n 在页模式下选择打印区域方向 例n=0","1B5400"},
												 {"ESC V n 选择/取消顺时针旋转90度 例n=0","1B5600"},
												 {"ESC W xL xH yL yH dxL dxH dyL dyH 页模式下设置打印区域","1B5700000000000000FF"},
												 {"ESC '\' nL nH 设置相对横向打印位置 例n=24","1B5C1818"},
												 {"ESC a n 选择字符对齐模式 例n=0","1B6100"},
												 {"ESC c 3 n 选择纸传感器输出纸尽信号 例n=2","1B633302"},
												 {"ESC c 4 n 选择纸传感器以终止打印 例n=1","1B633401"},
												 {"ESC c 5 n 允许/禁止按键 例n=1","1B633501"},
												 {"ESC d n 打印并向前走纸n行 例n=1","1B6401"},
												 {"ESC 1 n X0l X0h Y0l Y0h X1l X1h Y1l Y1h 划线指令 例n=0,X0l=0,X0h=255,Y0l=0,Y0h=255,X1l=255,X1h=255,Y1l=255,Y1h=255","1B6C0000FF00FFFFFFFFFF"},
												 {"ESC t n 选择代码页  例n=0","1B7400"},
												 {"ESC t n 选择/取消倒置打印模式  ","1B7B00"},
												 {"FS p n m 打印下载到NV存储器中的位图  例n=0,m=0","1B700000"},
												 {"FS q n [xL xH yL yH d1...dk]l...[xL xH yL yH d1...dk]n 定义NV位图  例n=1,xL=0,xH=1,yL=0,yH=1,d=0","1B71010001000100"},
												 {"GS FF n 标记纸定位","1D0C"},
												 {"GS ! n 选择字符大小 例n=0","1D2100"},
												 {"GS $ nL nH 页模式下设置纵向绝对位置  例n=0,n=0","1D240000"},
												 {"GS ( A pL pH n m 执行测试打印 例pL=2,pH=0,n=1,m=1","1D284102000101"},
												 {"GS ( E pL pH m d1 d2 (m=1) 用户自定义功能 例pL=3,pH=0,d1=73,d2=78","1D2845030001494E"},
												 {"GS ( E pL pH m d1 d2 d3(m=2) 用户自定义功能 例pL=4,pH=0,d1=79,d2=85,d3=84","1D28450400024F5554"},
												 {"GS ( E pL pH m [al b18...bll]...[ak bk8...bkl](m=3) 用户自定义功能 例pL=10,pH=10,a=1,b=48,k=1","1D28450A0A03013001"},
												 {"GS ( E pL pH m a (m=4) 用户自定义功能 例pL=2,pH=0,a=1","1D284502000401"},
												 {"GS ( F pL pH a m nL nH 设置打印起始位置和切纸位置参数 例pL=4,PH=0,a=1,m=48,nL=0,nH=0","1D2846040001300000"},
												 {"GS k pL pH n m 设置打印浓度  例pL=2,pH=0,n=49,m=3","1D282B02003103"},
												 {"GS ( M pL pH a n m 保存或装载由GS (F指令所定义的数据  例pL=2,pH=0,n=1,m=0","1D284D02000100"},
												 {"GS ( M pL pH n m ((n)=1,49) 例pL=2,pH=0,n=1,m=1","1D284D02000101"},
												 {"GS ( M pL pH n m ((n)=2,50) 例pL=2,pH=0,n=2,m=1","1D284D02000201"},
												 {"GS ( M pL pH n m ((n)=3,51) 例pL=2,pH=0,n=3,m=1","1D284D02000301"},
												 {"GS * x y d1...d(x*y*8)定义下载位图 例x=0,y=1,d=1","1D2A000101"},
												 {"GS / m 打印下载位图 例m=3","1D2F03"},
												 {"GS : 开始/结束宏定义","1D3A"},
												 {"GS B n 选择/取消黑白反显打印模式 例n=1","1D4201"},
												 {"GS C 0 n m 选择计数打印模式 例n=1,m=2","1D43300102"},
												 {"GS C 1 aL aH bL bH n r 选择计数模式(A) 例aL=1,aH=0,bL=255,bH=255,n=1,r=1","1D43310100FFFF0101"},
												 {"GS C 2 nL nH 选择当前计数值  例nL=1,nH=0","1D43320100"},
												 {"GS C ;sa;sb;sn;sn;sc;选择计数模式  例sa=1,sb=65535,sn=1,sr=1,sc=1","1D433B013BFFFF3B013B013B013B"},
												 {"GS H n 选择HRI字符的打印位置 例n=3","1D4803"},
												 {"GS I n 查询打印机 ID号  例n=1","1D4901"},
												 {"GS L nL nH 设置左边距  例nL=0,nH=0","1D4C0000"},
												 {"GS T n 设置打印起始位置在行首  例n=0","1D5400"},
												 {"GS V m 选择切纸模式并切纸  例m=0","1D5600"},
												 {"GS V m n 选择切纸模式并切纸  例m=66,n=0","1D564200"},
												 {"GS W nL nH 设置打印区域宽度  例nL=76,nH=2","1D574C02"},
												 {"GS '\' nL nH 页模式下设置纵向相对位置  例nL=1,nH=1","1D50101"},
												 {"GS ^ r t m 执行宏命令  例r=1,t=1,m=0","1D5E010100"},
												 {"GS a n 设置自动状态返回(ASB) 例n=0","1D6100"},
												 {"GS c 打印计数","1D63"},
												 {"GS f n 选择HRI使用字体  例n=1","1D6601"},
												 {"GS h n 选择条码高度 例n=162","1D68A2"},
												 {"GS k m d1...dk NUL n 打印条码","1D68490A7B424E6F2E7B430C2238"},
												 {"GS r n 返回状态 例n=1","1D7201"},
												 {"GS v 0 m xL xH yL yH d1...dk 打印光栅位图 例m=3,xL=0,xH=0,yL=255,yH=255,d=0","1D7630030000FFFF00"},
												 {"GS w n 设置条码宽度  例n=3","1D7702"},
												 {"FS ! n 设置汉字字符模式 例 n=4","1C2134"},
												 {"FS & 设置汉字模式","1C26"},
												 {"FS - n 选择/取消汉字下划线模式 例n=1","1C2D31"},
												 {"FS 2 c1 c2 d1...dk 定义用户自定义汉字 例c1=FEH,c2=FEH,d=0,k=72","1C32464548464548303732"},
												 {"FS S n1 n2 设置汉字字符左右间距 例n1=48,n2=48","1C5334383438"},
												 {"FS W n 选择/取消汉字倍高倍宽 例n=1","1C5731"}												 
											};
	
	public static final String[][] OrderMessage_Bold = {{"选择打印模式","SEL Printing Mode",""},
														{"标准ASCII字体(12*24)","Standard ASCII(12*24)","1B2100"},
														{"压缩ASCII字体(9*17)","Compress ASCII(9*17)","1B2101"},
														{"选择标准模式","SEL Standard Mode","1B53"},
														{"取消加粗模式","Canc Thicking Mode","1B4500"},
														{"选择加粗模式","SEL Thicking Mode","1B4501"},
														{"取消倍高模式","Canc Double H Mode","1B2100"},
														{"选择倍高模式","SEL Double H Mode","1B2110"},
														{"取消倍宽模式","Canc Double W Mode","1B2100"},
														{"选择倍宽模式","SEL Double W Mode","1B2120"},
														{"取消下划线模式","Canc Underline Mode","1B2D00"},
														{"选择下划线模式","SEL Underline Mode","1B2D01"},
														{"取消双重打印模式","Canc DoublePrint Mode","1B4700"},
														{"选择双重打印模式","SEL DoublePrint Mode","1B4701"},
														{"取消黑白反显打印","Canc BK WH AntiDisplay","1D4200"},
														{"选择黑白反显打印","SEL BK WH AntiDisplay","1D4201"},
														{"取消倒置打印","SEL Inversion","1B7B00"},
														{"选择倒置打印","Canc Inversion","1B7B01"}
													};
	
	public static final String[][] OrderMessage_Algin = {{"选择字符对齐模式","SEL CharAlign Mode",""},
														 {"左对齐模式","Left Alignment","1B6100"},
														 {"中间对齐模式","Middle","1B6101"},
														 {"右对齐模式","Right Alignment","1B6102"}
													 };
	
	public static final String[][] OrderMessage_Font = {{"选择字体","SEL Font",""},
		 {"标准ASCII字体(12*24)","Standard ASCII(12*24)","1B4D00"},
		 {"压缩ASCII字体(9*17)","Compress ASCII(9*17)","1B4D01"},
		 //{"用户自定义字符","1B4D02"},
		// {"汉字字体(24*24)","Chinese font(24*24)","1B4D03"}
	 };
	
	public static final String[][] OrderMessage_Hri = {{"选择HRI字符的打印位置","SEL HRI CharLocation",""},
		 {"不打印","No Printing","1D4800"},
		 {"在条码上方","Above the BarCode","1D4801"},
		 {"在条码下方","Under the BarCode","1D4802"},
		 {"在条码上方及下方","Above and below the BarCode","1D4803"}
	 };
	
	public static final String[][] OrderMessage_HriFont = {{"选择 HRI 使用字体","SEL HRI Font",""},
		 {"标准ASCII字体(12*24)","Standard ASCII(12*24)","1D6600"},
		 {"压缩ASCII字体(9*17)","Compress ASCII(9*17)","1D6601"},
	 };
	
	public static final String[][] OrderMessage_SetOffStart= {{"设置打印起始位置在行首模式","SET StartLocation",""},
		 {"清除打印缓冲区所有数据后，设置打印起始位置在行首","Clear CacheData,SET Start","1D5400"},
		 {"打印完缓冲区所有数据后，设置打印起始位置在行首","Clear CacheData after Print,SET Start","1D5401"},
	 };
	
	public static final String[][] OrderMessage_CharEncoding= {{"选择编码格式","SEL CodingMode",""},
		 {"UTF-8(标准)","UTF-8","1B7430"},
		 {"GB2312(中文)","GB2312(China)","1B7431"},
		 {"IBM852","IBM852","1B7412"},
		 {"ISO-8859-1","ISO-8859-1","1B7417"},
//		 {"PC850(多语言,西欧)","PC850(Multilingual)","1B7402"},
//		 {"PC860(葡萄牙)","PC860(Portugal)","1B7403"},
//		 {"PC863(加拿大-法语)","PC863(Canadian-Frensh)","1B7404"},
//		 {"PC865(北欧-德语)","PC865(Nordic German)","1B7405"},
//		 {"WPC1252(西欧)","WPC1252(West Europe)","1B7409"},
//		 {"PC866(西里尔文2)","PC866(Cyrillice*2)","1B7408"},
//		 {"PC852(拉丁语2)","PC852(Latin2)","1B7406"},
//		 {"PC858(西欧语)","PC858","1B7407"},
//		 {"PC737(希腊语)","PC737(Greek)","1B7418"},
//		 {"PC862(希伯来语)","PC862(Hebrew)","1B740F"},
//		 {"PC755(东欧)","PC755(East Europe)","1B7409"},
//		 {"Iran(伊朗)","Iran","1B740A"},
//		 {"CP775(波罗的海语)","CP775(The Baltic)","1B7419"},
//		 {"CP932(日文)","CP932(Japanese)","1B5208"},
//		 {"China(简体中文)","China","1B520F"},
//		 {"CP866(斯拉夫语/俄语)","CP866(Slavs/Rusian)","1B7407"},
//		 {"CP855(斯拉夫语)","CP855(Slavs)","1B741C"},
//		 {"CP857(土耳其语)","CP857(Turkey)","1B741D"},
//		 {"CP864(阿拉伯语)","CP864(Arab)","1B7416"},
//		 {"CP874(泰文)","CP874(Thai)","1B742F"},
//		 {"CP1250(中欧)","CP1250(Latin)","1B741E"},
//		 {"CP1251(西里尔文)","CP1251(Cyrillic)","1B7406"},
//		 {"CP1252(西欧(拉丁文))","CP1252(West Europe(Latin))","1B7410"},
//		 {"CP1253(希腊语)","CP1253(Greek)","1B7411"},
//		 {"CP1254(土耳其文)","CP1254(Turkish)","1B7420"},
//		 {"CP1255(希伯来文)","CP1255(Hebrew)","1B7421"},
//		 {"CP1256(阿拉伯文)","CP1256(Arabic)","1B7422"},
//		 {"CP1257(波罗的海文)","CP1257(The Baltic)","1B7419"},
//		 {"CP1258(越南)","CP1258(Vietnam)","1B7423"},
		 //{"PC861","PC861","1B7419"},
	 };
	
	public static final String printContent1 = "\n            HELLO" + "\n----------------------------"
			+ "\n BB：2015-01-01 16:18:20" + "\nCC：12378945664" + "\nDD：1001000000000529142"
			+ "\n BB：2015-01-01 16:18:20" + "\nCC：12378945664" + "\nDD：1001000000000529142"
			+ "\n BB：2015-01-01 16:18:20" + "\nCC：12378945664" + "\nDD：1001000000000529142"
			+ "\n BB：2015-01-01 16:18:20" + "\nCC：12378945664" + "\nDD：1001000000000529142"
			+ "\n BB：2015-01-01 16:18:20" + "\nCC：12378945664" + "\nDD：1001000000000529142"
			+ "\n BB：2015-01-01 16:18:20" + "\nCC：12378945664" + "\nDD：1001000000000529142";
	
	public static final String OrderMessage_Example_one = "1B40"
			+ "0A1B401B533333536C65637420756E6465726C696E65207072696E74206D6F646520"
			+ "1B2D024E6F7720697420776F726B7320212053656C65637420202020205072696E74206D6F646520"
			+ "1B210133333333333333"
			+ "1B2100204F70656E20696E766572736520207072696E74206D6F6465"
			+ "0A"
			+ "33333333334F4B210A333333"
			+ "33334F4B2133333333334E6F772049"
			+ "1D420033333333"
			+ "0A"
			+ "1D5600";
	
	public static final String OrderMessage_Example_two = "1B40"
			+ "0A"
			+ "1B4C"
			+ "1B572000000060022003"
			+ "5072696E7420496E2050616765204D6F646533333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
			+ "0C"
			+ "1D5600";
	
	
	public final static String customerCode1 = "G0AbYQEbMxgbKiHgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAOAAAfAAA/gAA/wAA/wAA/4AAf8AAf8wAP/wAH/wAH/wAD/wAB/wAB/wAB/wAH/wAH/wAH/wAP/wAP/wAP/wAf/wAf/wAf/wAf/wAf/wAf/wAf/wAf/wAP/wAv/wAf/wA//wB//wP//wP//w///x///z/8/z/4fz/gPz/AHx8ABwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPgAAAAAAAAAAAAAAAAAAAAAAAAAADgAAPwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAfwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAHwAAHwAAAAAAAAAAAAAAAAAAAAAAHwAAHwAAHwAADwAAAAAAAAAAHwAAHwAAHwAAHAAAHAAAHAAAHAAAHAAAHgAAHwAADwAABwAAAAAAAAAAEAAAHgAAHwAADwAAAwAAAAAAAAAAAAAAAAAACwAAHwAAHwAAHgAAAAAAAAAAAAAAAQAAAwAAHwAAHwAAHwAAHwAAHwAAAQAAAAAAAAAAAAAAAAAAHAAAHAAAHAAAHAAAHwAAHwAAHwAAHAAAHAAAHAAAHAAAAAAAAAAAAAAABwAADwAADwAAHwAAHAAAHAAAHAAAHgAADwAADwAAAwAAAAAAAAAAAAAAAAAAHwAAHwAAHwAAAAAAAQAAAwAAAwAABwAAHwAAHgAAHAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAHwAAHwAAHQAAHwAAHwAAAwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAHwAAHwAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAHwAAHwAAAAAAAAAAAAAAAAAAAAAAHwAAHwAAHwAAAAAAAAAAHAAAHAAAHAAAHAAAHwAAHwAAHwAAHAAAHAAAHAAAHAAAAAAAAAAAAAAAHwAAHwAAHwAAHAAAHAAAHAAAHAAAHAAAHgAAHwAADwAABwAAAAAAAAAAAAAAHwAAHwAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAHwAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAQAADwAAHwAAHwAAHwAAHwAABwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAQAAAAAAHwAAHwAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAQAAAQAAAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAQAAAQAAAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobKiHgAQAAAAAAAAAAAAAAAAAAAAAAAAAABwAAHwAAfwAB/wAD/wAP/wAf/wB//wD//wD/8AH/4A//gH//AP/+AP/4AP/wAP/wAP/gAP/AAP/AAP+AAP+AAP8AAP8AAP4ACP4A/vwB//4D//4H//wH//wH//wH//wH//wD//wD//wB/vwA/vwAAP4AAP4AAP4AAP4AAP4AAP4AB/8AH/+AP/+AP//Af//Af//gfz/wfx/wPx/4Pw/8Hwf+BwP/gAH/wAD/8AB//AA//gB//w//////////////////////////////+P/wAP4AAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAB/wAf/wX//////////////////////4//+A//wg//wA//wA//wA//wA//AD/gA/8AP4AAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAfwAH/wA//yP/////////////////////////////////////v/+AP/gAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAB/wAf/wH//z//////////////////////////////P//wP/8AP/AANgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AP//AAP/AAHAAAHAAAHAAP3AAF3AAF//AP//AAP/AAP+ANwAAAAAAA//AB//ABP/ABnAABnAAAngAAHwAAnwABv8ABe/ABcPAB4HAAwAAAAAAAAAAAAAAAIAAAPAAAP8AAH+AAw/ABx/ABH+ABvwAB/AAB4AAAAAABwDABwfABj/ABv+ABv4ABd4ABZ4ABx4AA94AAP4AA/4ABz+ABh/ABgPAPwBAHwAAAAAABgAABAAABf/ABf/AA//AAAAAAAAAAAAAAAAAAAAAAAAAEAwAPM8AD++AA+eAAOPAA/HAD/HAPHHAEHvAB3+ABz8AAB4AAAAAAAAABwAAAAAAP//AP//AAf/AA/gABvAABOAAAPgAA/4ABh+ABA/ABgfABwHABwAAAQAAAADAAAPAAQ/AB/+ABv4ABP4ABd4ABRwAA94AAP4AB/4AB/+ABh/ABgPAAgDABgAABQAABQAAAwAAAAAAAAAAAAAAAAAAAAAAAP/AAP/AAP/AMKnAMAHAMwHAPwHAPAHAEAHAHAHAMAAAMAAAMQAAHwAAHv8AAP+AAP/AAAPAAAHAAAHAAAHAAAPAAP/AAP8AAP4AAAAACAAAGAAAPwAAFwAAAAAAAP/AH//AP//AMAAAMAAAPwAAHwAAAAAAHwAAMAAAMP/AMP/AH//ACnAAH3AAH3gAMHwAMH4ANP+AH+/AAMPAAIHAHwAAPwAAMAAAMP/AP//AH//AAAAAAAAAAAAAAA4AAA+AAA+AEAPAMAHAMQHAMwPAPv+AOP+AMP4AAgAABgAABQAABQPABw/AAz/AAP8AA/4ABtwABJ4ABp4AB94AAP4AB/+ABz/ABg/ABADABwAABwAABQAABQAABwAAAQAAHwAAPwAABj4ABP+ABv+AA8HAAIDAAMDAAMGAAP/AAP/AAP/AAAAAAAAAAAAAAAHAAAHABwHABwEABgAABgAABwAAAwAAAD4AAP8AAP/AAOPAB4DAB8DABuPABv/AB/+AA38AAAQAAAAAAAAAAAHAAAHAAAHAAAAAAAAAAAAAAAAAAAAAGH8AMP+AMP/AMePAH4HAAoDACOPAHP/AMH+AMD4ANwAAHgAAAAAAAQHABwHADAHAHwAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobKiHgAQAAAAAAAAAAAAAAAAAAAC/8gP//8P///v///////////////////8AB/wAAfwAABwAAAQHgAAf4AA/4AB/8AB/+AB/+AB/+Ax/+Dx/+Hw/8Pw/4fwfwfwHgfwAAfwAAfwAAP4AAP4AAH8AAB/8AAP/wAP//wP///P///wf//wB//wAB/wAAHwAAAAAAAAAAAAAAAMADwPAP8Pgf+Pg//Pw//Pw//Px//vx//Pg//Pgf+PAP8OAH4AAAAAAAAQAABwAAH0AAv////////////////////////P//8P//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAHwAA/wAH/wAD/wAD/wAD/wAD/wAD/wAD/wAD/wAD/wAD/wAD/wAH/AADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAB/wDf/w///////////////////////////////////v//AP/wAP8AAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAD8AA/8Af/8H//8P//8P//8P//8P//8P//8P//8P//8P//8O7/8AD/8AD/9wD//wD//wD//wD//wD//wD//wD//wD//wD//wD//wD//wD//wD//AD8QACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAB8OAD/DACDBAEBhAEBjAEBuAGDMADHLAB8PAH/gAH/gAAAPAAEAAH/uAEZvAEZhAEZhAEZjAH9iADvAAAAGABhvAAApAAALAAAPADBvAHDgAEHgAEdgAH5gADxgAAAAAEAAAEHOwE/vYF4BYHgBYEALYDzPwH/AAEJvAEJvAEZgAD/GAAAPAD/NAH/pAEBrAEBvAH/gAD/OAAAPAB3BAHxjAExvAEzvAE/AAEeHADANAHBpAEHrAEHvAGdgADxgAAAAADBgAHDgAEHgAEdgAH5gADxoAAAOAD/HAEZuAEZoAEZgAH/AADmOAAAPABABADABAH/jAD/PAAAAAAAPABzPAHzoAGxuAExnAE/hAEeAAAAPAD/BAEZhAEZhAEZvAH/KADvMAAAPAAB/AAB8AAAKAAAHAAANAAAJAAALAH/vAH/AAAAPAH/PAH/gAEZgAEZnAEZtAE5pAH/LADvPAADgAA+AAD8AAHkAAHsAAD8AAAPAAADgAAAAAAAAAH/vADgIABwAAA4AAAOBAAHDAH/nAAANABhpABhhAAAAAH/BwH/hwAYAAAYAAAYAAAYAAH/AAH/gAAAAAH/gAEYAAEYAAEYPAEYPAEeAAH7AADxuAAAPAD/BAH/hAEBvAEBuAH/gAD/OAAABAHBhAEDhAEHvAEdsAH5uAAAPADBhAHDhAEHlAENuAH5gADxgAAAOADHPAHBhAEZhAEZvAH/OADuAAAMAAA8AAB0AADEAAH/gAD9DAAAPAD/PAH/pAEBhAEBhAH/hAD/GAAAPAD/JAH9rAEBvAEBvAH/gAD/OwAIBYH/BYEBjYEBvwEBggH/PAAAPADzAAH7gAEJvAEJpAH/pAD/JAAALAAAAADAPAH/PAH/jAAABAAANABAOADAAAH/gAH/hwAABgAAAAD/AAH/gAEBgAEBgAHFgAD/AAAAP4D/P4H/hAEBhAEBvAH/uAD/AAAABAD/BAEBgAEBv4EBvwH/BAD+BAAAPABAOADAAAH/gAF9BAAAAAAAAAD/AAH/gAEBgAEBgAH/gAD/AAAABAD/HAEZtAE1tAExpAHfAACMBABzDAHzHAHxtAExpAEzhAEeMAAAMAAAMADAMAHVPAH/vAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobKiHgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAPAAAPwAAP4AAP8AAP+AAP/AAP/gAP/wAD/4AB/4AA/8AAf+AAP+AAP+AOH/APD/APj/gPh/gPh/wPg/wPgfwPg/4Pg/4PAf4OAf4IAf8AAf8AAf8AAf8AAf8NAf8P//8P//8P//8P//8A//4AD/4AAf4AA/wAA/wAB/wAB/gAD/gAD/gAH/AAP/QAP/4Af/4A//4B//4D//4P//4P//4P//4P//4P//4P//4P//4Ph/4OB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/wAf+AH/gAP8AANAAAAAAAAAAAAAAAAAD4AA/4BP/4P//4P//4P//4P//4Px/4MB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AD/4A//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P9/4PB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4AB/4Bf/4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//AP/wAP8AAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gAH/gAGZgAGZgAGZgAGZgAH/gADvAAAXAAA/gAAtgAAtgAAtgAA9AAAAAAAZAAA9gAAtgAAmgAA3gAATAAAAAAA/8AAxgAAhgAAhgAA/gAAfAADrgAH/gAAAAAAAAAAzAAAngAAtgAAtgAA/gAAWgABvAAD/gAAhgAAggAACAAA/gAAwAAAgAAAgAAA/gAAAAAG/gAG/gAAAAAAAAAAAAAAAAAAAAAAAAAG/gAAAAAA/gAA/gAAwAAAgAAA/gAAfgAAgAAD/gAH/gAGgAAAfAAA/gAAhgAAhgAA/gAAfAAAAAAAAAAAAAAAAAAAAAAAgAAD/gAD/gAAggAAAAAAfAAA/gAAtgAAtgAA9gAAdAAAAAAH/gAAgAAAfAAA/gAAtgAAtgAAtgAAdAAAgAAD/gAH/gAGgAAAfAAA/gAAhgAAhgAA/gAAfAAAAAAA/gAA/AAAgAAAgAAA/gAAfgAAAAAAhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAH9gAGBgAGAgAH/gAD/AAAAAAD/gAGZgAGZgAGZgAD/AAAAAAD/AAH/gAGBgAGBgAH/gAD/AAAAAAD/AAH9gAGBgAGBgAH/gAD/AAAAAAAAAAAAAAAAAAAAAABAAAD/gAGZgAGxgAGxgADfAAAAAAD/AAH/gAGBgAGBgAH/gAD/AAAAAAD/AAG/gAGBgAGAgAH/gAD/AAAAAAAAAAAAAAAAAAAAAABIAAD/AAGZgAGxgAGxgADfAAAAAAD/AAH/gAGBgAGBgAH/gAD/AAAAAAGAAAGGAAGfgAH8AAHgAAGAAAAAAAAAAAAAAAAAAAAAEAAyEAAfkAAHkAAeEAA4GAA8GAAHkAAfkAA+EAA+GAAHkAAeGAA8GAA8GAAeGAAHkAA+GAA+EABPmAAHkAA+GAA8GAAeEAAHmAAfkAA2GAAAmAABmAAAEAAAGAH/kAAAGAAAEAA/GAA/kAABkAABmAA/kAA/mAAgEAD/kAAhkAAgkAA/mAA/mAAgEAAgEAG/mAG/kAAAMAA+sAG/+AAAEAATEAA3mAAtmAAtmAA/mAAfkAAAGAAAGAAAkAAAGAAAGAH/kAD2EAAgGAAgEAA/kAAfkAAgGAA/kAAwEAAgEAAgEAAAAAAAAAAAAAAAAAAAAAAAAAobKiHgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobMhtkARshAVRyaWxpeCBkLm8uby4sIFRyaWxpeAobIQAbIQFaYWdyZWIsIE1pcmFtYXJza2EgMjQKGyEAG2QBG0UxUE9UVlJEQSBPIFVQTEFUSQobRTA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQobIRAbRTFUViBCaW5nbyAgICAgICAgICAgICAgICAgICAgICAgICBLb2xvIDAwMQobRTAbIQA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQpVUExBVE5JIEJST0ogICAgICAgICAgICAgICAgICAwMDAwMCAwMDAwMgotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQobIQFWUklKRU1FIElaVkxBrEVOSkEgICAgICAgICAgICAgICAgMDcuMDEuMjAxOS4gdSAxODoyMCBoChshAD09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ClBST1ZKRVJBIERPQklUS0EKU01TIEtPRCAbRTEqKlRFU1QqKgobRTAbIQFQb+dhbGppdGUgU01TIGtvZCBuYSBicm9qIBshABtFMTYxMzEzNiAoMSw4NiBrbi9wb3J1a2EpChtFMBshAWlsaSBwcm92amVyaXRlIGJlc3BsYXRubyBuYSAbIQAbLTF3d3cubHV0cmlqYS5ocgobLTAbIQFSZXp1bHRhdGkgZG9zdHVwbmkgMiBzYXRhIG5ha29uIGl6dmxhn2VuamEKGyEAPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KQklOR08gMTUgT0QgOTAgS09NQklOQUNJSkUKGyEBLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tChshACAxIDExIDI4IDc5IDg0CjI1IDQwIDY0IDc1IDg5CjM4IDQ2IDUxIDY3IDc0ChshAS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQobIQAxOCAyMyAzNiA0OSA2OQogOCAxNCAyMSAzNSA4MQogNyAyNyA0MSA1OCA3NgobIQEtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KGyEAIDQgMTUgNDQgNTQgNjUKMTIgMjYgMzQgNDMgNTIKIDMgMTkgNjIgNzIgODIKGyEBLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tChshACA1IDE2IDI5IDU3IDg1CjIwIDMyIDQ3IDU5IDYxCiAyIDUzIDY4IDcxIDg2ChshAS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQobIQAxMyAzMSA0OCA2MyA4NwoxMCAzNyA0NSA1NSA2MAogNiAyNCAzMyA3MyA4MAobIQEtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KGyEAMTcgMjIgNTAgNzAgODgKIDkgMzkgNjYgNzggODMKMzAgNDIgNTYgNzcgOTAKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KQklOR08gMjQgT0QgNzUgS09NQklOQUNJSkUKGyEBLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tChshACA2IDE2IDQ1IDQ2IDY3CiAzIDE4IDM5IDU3IDY5CjEwIDI1IC0tIDU1IDYxCiAyIDI2IDM0IDUzIDYyCiAxIDI4IDQ0IDYwIDczChshAS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQobIQAgNCAyNCAzOCA0OCA2NAogOCAzMCA0MiA1NiA3MgoxMiAxOSAtLSA1OCA3MAogNyAyMiAzNiA1NCA2NQoxMSAyMSA0MCA1MCA2OAobIQEtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KGyEAMTMgMjAgMzEgNTIgNjMKMTQgMTcgMzUgNTEgNjYKIDUgMjkgLS0gNDkgNzUKIDkgMjcgNDEgNDcgNzEKMTUgMjMgMzIgNTkgNzQKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KQmluZ28gcGx1cyBicm9qZXZpG0UxICAgICAgICAgICAgICAgIDI5MDYwMTQKG0UwG0UxICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDcxMDI3NTEKG0UwG0UxICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDY0NDc3MjUKG0UwPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KU2VyaWpza2kgYnJvaiBsaXN0aYZhG0UxICAgICAgICAgOTk5IDAwMDA5NDgKG0UwPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KGyEQG0UxSXpub3MgdXBsYXRlID0gKjI0LDAwIGtuChtFMBshABtkARshAVVwbGF0b20gaWdyZSBuYXZlZGVuZSBuYSBvdm9qIHBvdHZyZGkgaWdyYZ8gcG90dnLQdWplCmtha28gamUgdXBvem5hdCBzIHByYXZpbGltYSBpZ3JlIHRlIGlzdGEgdSBjaWplbG9zdGkKcHJpaHZhhmEKGyEAG2QBOTItNDI2ICAwMi4wMS4yMDE5Li8xMjo1NjoyMwodSAAdZgAdaG4ddwIda0kMe0MQWV4yEwAAAAACG0UxMTY4OTk0NTAxOSAwMDAwMDAwMDAyG0UwG2QBrFVWQUpURSBTVk9KVSBQT1RWUkRVLAobIQFvbmEgamUgamVkaW5pIERPS0FaIFpBIFNVREpFTE9WQU5KRSBVIElHUkkuChshABshAU5lIGl6bGGnaXRlIGplIHV0amVjYWp1IHZsYWdlIGkgamFrb2c";

	public final static String customerCode2 = "G0AbYQEbMxgbKiEAAQAAAAAAAAAAAAAAAAAAAAAAAwAABwAADwAAHwAAPwAAfwAAfwAA/wAB/wAB/wAD/wAD/wAD/gAH/gAH/AAH/AAH+AAH+AAH+AAP+AAP+AAP+AAH+AAH+AAH/AAH/AAH/AAH/gAD/gAD/wAB/wAB/wAB/wAA/wAAfwAAfwAAPwAAHwAADwAAAwAAAQAAAAAAAAAAAAAAAAABgAAB8AAB/AAD/wAD/wAD/wAD/wAD/wAH/wAH/wAB/wAAPwAADwAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAHwAAfwAB/wAH/wAD/wAD/wAD/wAD/wAD/wAB/wAB+AAB4AABgAAAAAAAAAAAAAAAAAAAAwAADwAAHwAAfwAAfwAA/wAA/gAB/AAB+AAD+AAH+AAH8AAP8AAP8AAf4QAf4QA/4wA/wwA/xwA/xwA/jwA/jwA/jgA/DAA/CAA/CAA/DAA/jgA/jwA/jwA/xwA/xwA/wwA/4wAf4QAf4QAP8AAP8AAH8AAH+AAD+AAB+AAB/AAA/wAA/wAAfwAAfwAAHwAADwAAAwAAAAAAAAAAAAAAAAAH/gAH/gAH/gAH/gAH/gAH/gAH/gAH/gAH/h///x///z///z///z///3///3///////////////wAH/gAH/gAH/gAH/gAH/gAH/gAH/gAH/gAH/gAH/gAH/gAH/gAH/gAD/gAAAAAAAAAAAAABgAAB4AAB+AAB/gAD/wAD/wAD/wAD/wAD/wAH/wAD/wAAfwAAHwAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAADwAAPwAB/wAH/wAH/wAD/wAD/wAD/wAD/wAD/wAB/AAB8AABwAAAAAAAAAAAAAAAAAAAAAAAAAobKiEAAQB//gf//x///3////////////////////////////+P8PwP8PAP8OAP8MAP8IAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8IAP8MAP8PAP8PwP8P8P8P//8P//8P//8P//8P//8P//8P//8D//8Af/8AD/8AAAAAAAAAAAAAAAAMAAAPgAAP4AAP+AAP/gAP/8AP//AP//wP//+P///n///x///wP//wD//wA//wAH/wAB/wAAPwAADwAAAwAAAAAAAAAAAAAAAAAAAAAAAwAADwAAfwAB/wAP/wA//wH//wf//x///////////P//8P//wP/+AP/4AP/gAP+AAPwAAPAAAMAAAAAAAAAAAAAAAAH//wf//x///3/////////////+///wH/+AA/wAAOAAAAB+/AH8fwP4Pw/gDz/AB3+AA38AAfwBAPgHwPA/+PD//uH//8H//4P//wP//wf//wf//wf//w///w///wf//wf//wf//wP//4P//8H//+H///D//vA/+PgHwPwBAH8AAX+AAz/ABw/gDwP4PwH8fwB+/OAAAPwAAP+AA//wH//+/////////3///x///wf//wH//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAPAAAPwAAP8AAP/gAP/4AP/+AP//gP//8P///P///z///wf//wH//wA//wAP/wAD/wAAfwAAHwAAAwAAAAAAAAAAAAAAAAAAAAAAAQAADwAAPwAB/wAH/wAf/wD//wP//x///3///////v//+P//4P//AP/8AP/wAP+AAP4AAPgAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobKiEAAQAAAOAAAPgAAP4AAP8AAP/AAP/gAP/wAP/4AP/8AP/+AD/+AA//AAf/gAP/gAH/wAD/wAB/wAB/4AA/4AA/4AA/4AAf8AAf8AAf8AAf8AAf8AAf8AAf8AAf8AAf8AAf4AA/4AA/4AA/4AB/4AB/wAD/wAH/gAH/gAP/AAf/AA/+AAf8AAH8AAD4AABwAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAOAAAPwAAP8AAP/AAP/wAP/+AP//gP//wP//4H//4B//4Af/4B//4P//4P//4P//wP//AP/8AP/wAP/AAP4AAPgAAOAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAMAAAPAAAPwAAP4AAP+AAP/gAP/4AP/8AH/8AA/+AAD+AAB/AIA/gOA/gPg/wPwfwPwf4H4f4D8P8B8P+A+P+A+H+AfH+IPn+IHj+MHj+MDj+OBh+OAh+OAh+OBh+MDj+MHj+IHj+IPH+AfH+A+H+B+P+B8P8D8P8H4f4Pwf4PwfwPg/wOA/gIA/gAB/AAH+AA/+AH/8AP/8AP/wAP/gAP+AAP4AAPwAAPAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAP/wAP/8AP/+AP//AP//gP//wP//wP//4P//4AH/4AB/8AA/8AA/8AA/8AAf8AAf8AAf8AAf8AAf8AA/4AA/4AA/4AB/wAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAPgAAP4AAP+AAP/wAP/8AP//AP//wP//4P//4D//4Af/4A//4H//4P//4P//wP//gP/+AP/4AP/AAP8AAPwAAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobKiEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobMhtFMSAgSkVETk9TVEFWTk8uChtFMBtkAURhdHVtIGkgdnJpamVtZSBrdXBuamU6IAoxMC0wMS0yMDE5LzEwOjI0OjI1CklEOiBXVFJJMDAwMQobZAE9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQobIRAbRTEzIG1qZXNlY2Egc3ZpIGJ1a2V0aSArIEhCTyBpIENpbmVtYXgKG0UwGyEAG0UxNTAwLDAwIGtuChtFMBtkAT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ChtFMWV2b3R2IG5hIGJvbm92ZQobZAEbRTAbIQEbRTFFdm90diBWaWRlb3Rla2ENChtFMBshABshARtFMVV6IG92YWogYm9uIGRvYml2YecgZXZvdHYgVmlkZW90ZWt1CnBvdHB1bm8gG0UwGyEACmJlc3BsYXRubyB6YSB2cmlqZW1lIHRyYWphbmphIGt1cGxqZW5vZwpwZXJpb2RhIApldm90diB1c2x1Z2UuUmVnaXN0cmlyYWogc2UgbmEKGyEBG0UxIG1vai5ldm90di5ocg0KG0UwGyEAGyEBG0UxICBpIHByZXV6bWkga29kIHphIGFrdGl2YWNpanUgVmlkZW90ZWtlLg0KG0UwGyEACj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ChtkATE0LXpuYW1lbmthc3RpIGFrdGl2YWNpanNraSBrb2Q6ChtFMTEzODk5MTAwMDAwMDAwChtkARtFME5hZG9wbGF0YSBTTVMgcG9ydWtvbToKUG/nYWxqaXRlIDE0LXpuYW1lbmthc3RpIGtvZCBzIGUtYm9uYQppIHJhem1hayB0ZSAxMS16bmFtZW5rYXN0aSBicm9qCmtvcmlzbmmfa29nIHVyZdBhamEgbmEgYnJvaiAwOTUgMTAwIDY2NzcKUHJpbWplcjogMDEyMzQ1Njc4OTEyMzQgMDEyMzQ1Njc4OTEKG2QBG0UxTmFwb21lbmE6ChtFMFNNUyBwb3J1a2EgbmFwbGGGdWplIHNlIHN1a2xhZG5vIGNqZW5pa3UKVmHnZWcgbW9iaWxub2cgb3BlcmF0ZXJhLgobZAFWaedlIG8gdXNsdXppIGkgb3CGaW0gdXZqZXRpbWEKcHJvbmHQaXRlIG5hIHd3dy5ldm90di5ocgobZAFFdm90diBzbHWnYmEgemEga29yaXNuaWtlIDA4MDAgMDcwNwobZAFTZXJpanNraSBicm9qIGUtYm9uYTogNDQxOTcKQWt0aXZhY2lqc2tpIGJvbiB2cmlqZWRpCjYwIGRhbmEgb2QgZGF0dW1hIGt1cG5qZQodKGsRADFQMDEzODk5MTAwMDAwMDAwHShrAwAxRTIdKGsDADFDBh0oawMAMVEwMTM4OTkxMDAwMDAwMDAKG2QBPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KGyEQG0UxQ2lqZW5hIGJvbmE6IDUwMCwwMGtuChtFMBshACh1IGNpamVudSBqZSB1a2xqdZ9lbiBQRFYpCj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ClRyZ292YWM6IFRyaWxpeCBkLm8uby4KUHJvZGFqbm8gbWplc3RvOiBUcmlsaXgKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KG0UxUG93ZXJlZCBieSBUcmlsaXgKG0UwPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KG2QJ";

	public static final  String customerCode3 = "G0AbYQEbMxgbKiHuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAABwAADwAAPwAA/wAD/wAP/gA//AH/8Af/wA//AA/8AA/gAA+AAA+AAA+AAA+AAB+AAB+AAB8AAB8AAB8AAB8AAB8AAB8AAD8AAD4AAD4AAD4AAD4AAD4AAD4AAH4AAH4AAH///3///3///3///3///38AAH+AAD/AAA/gAAfwAAP//wH//wD//wB//wA//wAAAAobKiHuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAABwAAHwAAPwAAfwAAfwAA/gAA/AAB+AAB+AAD8AAD8AAH4AAH4AAPwAAPwAAfgAAfgAA/AAA/AAB+BwB+PwB//wD//wD//wH//AH/4AH/gAH8AAHwAAH4AAH4AAD4AAD4AAD4AAD8AAD8AAB8AAB8AAB8AAB+AAB+AAA+AAA+AAA+AAA/AAA/AAAfAAAfAAAfAAAfgAAfgAAPgAAPgAAPgAAPgAAPwAAHwAAHwAAHwAAHwAAH4AAD4AAD4AAD4AAD4AAD+AAB/wAB/wAB/wAA/wAAHwAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAHwAAPwAAPwAAfwAA/wAA/AAB+AAB+AAD8AAH8AAH4AAPwAAfwAAfgAA/AAB/AAD+AAD8AAH8AAP4AAfwAA/gAB/AAD+AAH+AAP8AAP4AAPwAAPAAAOAAAMAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAobKiHuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAHwAA/wAH/wA//wD//gf/+D//wP/+AP/wAP+AAP4AAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAQAADwAAfwAD/wAf/wD//wf//D//4P//AP/4AP/AAP4AAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAP4AAP/AAP/8AP//gD//8Af//wD//wAP/wAB/wAAHwAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////////wAAAwAAAwAABwAABwAADwAADwAAHwAAHwAAPwAAfwAAfgAA/AAB/AAB+AAD8AAH8AAH4AAPwQAfwQA/gwB/AwD+BwH8DwP8Dwf//wf//wf//wf//wf//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAobKiHuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAADwAAfwAD/wAf/wB//wP/+B//4P//AP/4AP/AAP8AAPgAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAHwAAfwAD/wAf/wD//wf/+D//wP/+AP/wAP+AAP4AAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAHwAA/wAH/wA//wB//wD/+AD/wAD/wAD/+AB//wA//wAH/wAA/wAAHwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAP4AAP/AAP/4AP//gH//8Af//gD//wAP/wAB/wAAPwAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAPwAAP4AAP4AAP4AAP4AAP4AAP4AAP4AAP4AAP4AAP4AAL8AAL8AAB8AAB8AAB8AAB8AAD8AAH4AAH4AAPwAAPwAAPgAAPgAAPAAAPAAAOAAAOAAAMAAAP///////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAobKiHuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAABwAAPwAB/wAP/wA//wH//A//8H//gP/8AP/gAP+AAPwAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAHwAA/wAH/wA//wH//w//+H//wP/+AP/wAP+AAPwAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAADwAAfwAD/wAf/wD//wf//H//4P//AP/4AP/+AP//wP///Af//wB//wAH/wAA/wAAD4AAAPAAAP4AAP/gAP/8AP//gD//+AP//wB//wAP/wAA/wAAHwAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAPwAAP/AAP/4AP//AH//8A///gD//wAf/wAB/wAAPwAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAobKiHuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAHwAA/wAH/wAf/wD//gf/+D//wP/+AP/wAP/AAP4AAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAPwAB/wAP/wB//wH//g//8H//gP/8AP/gAP8AAPgAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAPwAB/wAP/wB//wP//h//8P//gP/8AP/gAP8AAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAPgAAP+AAP/4AP//gP//8A///wH//wAf/wAB/wAAPwAAAwAAAPAAAP4AAP/AAP/8AP//gD//+Af//wB//wAP/wAB/wAAHwAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAPwAAP+AAP/4AP//AH//4A///gD//wAf/wAD/wAAPwAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAAAAAAAAAAAAAAAAP///////////////////wAAAAobKiHuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAADwAAfwAD/wAf/wB//wP//B//4P//AP/4AP/AAP8AAPgAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAABwAAPwAB/wAP/wB//wP//B//4P//AP/8AP/gAP8AAPgAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAH8AA/+AH//AP//AP//AP+/APw/AOA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/AAA/APA/AP4/AP//AP//AP//AD//AAP/AAB/AAA/AAA/AAA/AAA/AAA/AOA/AP4/AP//AP//AP//AD/+AAf+AAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAPwAAP+AAP/wAP//AP//4A///gH//wAf/wAD/wAAfwAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/AAP/gAP/gAP/gAP/gAAPgAAPgAAPgAAPwAAPwAAPwAAHwAAHwAAHwAAHwAAHwAAHwAAHwAAHwAAHwAAH4AAH4AAD4AAD4AAD4AAD4AAD4AAD4AAD4AAD4AAD4AP/4AP/8AP/8AP/8AP/8AAH4AAP4AAPwAAfgAA/gAP/AAP+AAP+AAP8AAPwAAAAAAAobKiHuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAPwAB/wAP/wA//wH//g//8H//gP/8AP/gAP+AAPwAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAADwAAfwAD/wAf/wD//wf//D//4P//AP/4AP/AAP4AAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAABwAADwAAHwAAHwAAPwAAPwAAPwAAPwAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAfgAAfgAAfgAAfgAAfgAAfAAAfAAAfAAAfAAAfAAAfAAAfAAAfAAAfAAAfAAAfAAAfAAAfAAAfAAA/AAA/AAA/AAA/AAA/AAA+AAA+AAA+AAA+AAA+AAA+AAA/wAA/wAA/wAA/wAA/wAA+wAA+AAA+AAB+AAB+AAB+AAB+AAB+AAB/AAB/wAA/wAA/wAAfwAADwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAPgAAP+AAP/wAP/+AP//4A///AH//wA//wAD/wAAfwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobKiHuAAAAAAAAAAAAAAAAAAAAAwAAHwAA/wAH/wAf/wD//gf/+D//wP/+AP/wAP/AAP4AAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAHwAA/wAD/wAf/wD//wf/+D//wP/+AP/wAP+AAP4AAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAfwAH/wA//wP//x///P//4P/+AP/wAP8AAPAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAP8AAP/wAP//AP//8D///wP//wA//wAD/wAAPwAAAwAAAwAAAYAAAfAAAf8AAf/gAf/8Af//wD//+AP//wB//wAP/wAA/wAAHwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAwAAAwAAA8AAA/gAA/8AA//wA//+A///5x///wH//wA//wAH/wAAfwAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobKiHuAAAAAAPgAB/4AP/4AP/8AP/8AP9+APh+AMA/AAA/AAAfgAAfgAAPwAAPwAAH4AAH4AAD4AAD8AAB8AAB+AAB+AAH/AA//AH//A///H//+P/++P/w+P+A+PwA+OAB+AAB+AAB8AAB8AAB8AAB8AAB8AAB8AAD8AAD8AAD4AAD4AAD4AAD4AAD4AAH4AAH4AAH4AAHwAAHwAAHwAAHwAAHwAAPwAAPwAAPwAAPgAAPgAAPgAAPgAAPgAAfgAAfgAAfAAAfAAA/AAH/AA//AP/+AP/8AP/wAP+AAPgAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAOAAAOAAAOAAAPAAAPAAAPAAAPAAAPAAAPgAAPgAAPgAAPgAAPgAAPgAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPwAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAPgAAPAAAPAAAPAAAPAAAPAAAPAAAPAAAPAAAOAAAOAAAOAAAOAAAOAAAOAAAOAAAOAAAMAAAMAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAobMhtkAUExIEhydmF0c2thIGQuby5vLgobIQFEYXR1bS9WcmlqZW1lOiAyOC0xMi0yMDE4LzExOjM3OjE3ChshABshAVRyZ292YWM6IFRyaWxpeCBkLm8uby4KGyEAGyEBUHJvZGFqbm8gbWplc3RvOiBUcmlsaXgKGyEAGyEBSUQ6IFdUUkkwMDAxChshAD09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ChtFMUNpamVuYQobRTAbRTFBMSBlLWJvbiA1NSwwMCBrbgobRTA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQpPVk8gSkUgVEVTVCBCT04hCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tChshAVphIG9ibm92dSBBMSByYZ91bmEgbmEgYm9ub3ZlIGtvcmlzdGl0ZSBvdmFqIGJyb2o6ChshABtFMVhYWFhYWFhYWFhYWDExChtFMC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tChshAVN2b2ogQTEgcmGfdW4gbmEgYm9ub3ZlIG1vp2V0ZSBvYm5vdml0aSBuYSBkdmEgbmGfaW5hOgobIQAbZAEbIQExLiBVdGlwa2FqdGUgKjEwMypYWFhYWFhYWFhYWFgxMQobIQAbIQFpIHByaXRpc25pdGUgdGlwa3UgemEgcG96aXYKGyEAGyEBaWxpChshABshATIuIG5hem92aXRlICAwOTEgNzcgODggMDAwIGkgc2xpamVkaXRlChshABshAWdsYXNvdm5lIHVwdXRlChshABtkARshAUExIGUtYm9uIHZyaWplZGkgZG86IDIwMjQtMDctMDcKGyEAGyEBU2VyaWpza2kgYnJvaiBib25hOiA3NDg3MjQ2OQobIQAbZAEbIQFTbHWnYmEgemEga29yaXNuaWtlIDAtMjRoOiAwODAwIDA5MSAwOTEKGyEAGyEBRG9kYXRuZSBpbmZvcm1hY2lqZSBtb6dldGUgcHJvbmGGaSBuYQobIQAbIQEbRTF3d3cuQTEuaHIKG0UwGyEAGyEBSHZhbGEgbmEgcG92amVyZW5qdSEKGyEAHUgCHWYAHWhuHXcDHWtDDTM4NTg4ODg3NjcyMDQbZAEbIQEbRTFDaWplbmEgb2QgNTUsMDAga24gdWtsanWfdWplIFBEViBpIG5ha25hZHUgemEKa29yaed0ZW5qZSBtcmWnZSBkZWZpbmlyYW51IENqZW5pa29tIGRvc3R1cG5pbQpuYSB3d3cuQTEuaHIKGyEAG0UwG2QBPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KG0UxUG93ZXJlZCBieSBUcmlsaXgKG0UwPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KG2QJHVYB";

}
